name: build

on:
  push:
    paths:
      - 'airsaned/**'
      - '.github/**'

  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        wrtrel: ['22.03.6', '23.05.3']
        sdk: ['ramips-mt7621']

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.sdk }}-${{ matrix.wrtrel }}
          EXTRA_FEEDS: src-git|airsaned|https://github.com/nevian427/AirSane-openwrt.git^${{ github.sha }}
          PACKAGES: airsaned

      - run: bash ./.github/work.sh pkg-ver airsaned/Makefile | tee $GITHUB_ENV
        shell: bash

      - uses: actions/upload-artifact@v3
        with:
          name: airsaned_${{ env.PKG_FULL_VERSION }}_openwrt-${{ matrix.wrtrel }}_${{ matrix.sdk }}.ipk
          path: bin/packages/**/airsaned_*.ipk
